select * from gold.dim_customers;
select * from gold.dim_products;
select * from gold.fact_sales;

-- explore all objects from database
select * from INFORMATION_SCHEMA.TABLES;

--explore all columns
select * from INFORMATION_SCHEMA.COLUMNS 
where TABLE_NAME='fact_sales';

select * from INFORMATION_SCHEMA.COLUMNS 
where TABLE_NAME='dim_customers';

select * from INFORMATION_SCHEMA.COLUMNS 
where TABLE_NAME='dim_products';


--explore all countries the customers come from
select distinct country from gold.dim_customers;

--explore all categories the customers come from
select distinct category from gold.dim_products;

-- explore all categories "The major divisions"
select distinct category,subcategory,product_name 
from gold.dim_products order by 1,2,3;

--earliest and lastet date boundaries
-- find first and last order date
--how many years of sales are available
select min(order_date) as first_order_date, max(order_date) as last_order_date,
DATEDIFF(year,min(order_date),max(order_date)) as order_data_years from gold.fact_sales;

--find youngest and oldest customers
select min(birthdate) as oldest, DATEDIFF(year,min(birthdate),(select max(order_date)
from gold.fact_sales)) as age
from gold.dim_customers;

--Measure Exploration

--Total Sales
select sum(total_sales) as total_sales from gold.fact_sales;

--How many items are sold
select sum(quantity) as total_quantity from gold.fact_sales;

--average selling price
select avg(price_per_unit) as average_selling_price from gold.fact_sales;

--total number of orders
select count(distinct order_number) as total_distinct_number_of_order
from gold.fact_sales;

--total number of products
select count(product_key) as total_product
from gold.dim_products;

--total number of customers
select count(customer_key) as total_customers
from gold.dim_customers;

--total number of customers that placed an order
select count(distinct customer_key) as number_of_customer_ordered
from gold.fact_sales;

--Generate a report that contains all the key metrices of the business

select 'Total sales' as measure_name, sum(total_sales) as measure_value from gold.fact_sales 
union all
select 'Total Quantity' as measure_name, sum(quantity) as measure_value from gold.fact_sales
union all
select 'Average Selling Price' as measure_name, avg(price_per_unit) as measure_value from gold.fact_sales
union all
select 'Total Orders' as measure_name, count(distinct order_number) as measure_value from gold.fact_sales
union all
select 'Total Product' as measure_name, count(product_key) as measure_value from gold.dim_products
union all
select 'Total Customers' as measure_name, count(customer_key) as measure_value from gold.dim_customers
union all
select 'Total Ordering Customer' as measure_name, count(distinct customer_key) as measure_value
from gold.fact_sales;


--Magnitude analysis

--Total customers by countries
select country,count(customer_key) as total_customers_by_country from gold.dim_customers group by country;

--Total customers by gender
select gender,count(customer_key) as total_customers_by_gender from gold.dim_customers group by gender;

--Total products by categories
select category,count(product_key) as total_products_by_category from gold.dim_products group by category;

--Average cost in each category
select category, avg(cost) from gold.dim_products group by category;

--Total revenue generated for each category
select a.category, sum(total_sales) as avg_cost_in_category from gold.dim_products a right join gold.fact_sales b on
a.product_key=b.product_key group by a.category;

--total revenue generated by each customer
select a.first_name,a.last_name, sum(total_sales) as total_revenue_by_customer from gold.dim_customers a left join gold.fact_sales b on
a.customer_key=b.customer_key group by a.first_name,a.last_name;

--distribution of sold items across the countries
select a.country, sum(quantity) as total_distribution_across_countries from gold.dim_customers a right join gold.fact_sales b on
a.customer_key=b.customer_key group by a.country;


--ranking analysis
--which of the 5 products generate the highest revenue
select top 5 product_name,sum(total_sales) as total_sales  from gold.fact_sales a left join gold.dim_products b
on a.product_key=b.product_key group by product_name order by total_sales desc;

select product_name,total_sales from (
	select product_name,sum(total_sales) as total_sales,rank() over(order by sum(total_sales) desc) as rnk from gold.fact_sales a left join gold.dim_products b
	on a.product_key=b.product_key group by product_name)t
where rnk<=5;


--which of the 5 products generate the lowest revenue

select top 5 product_name,sum(total_sales) as total_sales  from gold.fact_sales a left join gold.dim_products b
on a.product_key=b.product_key group by product_name order by total_sales asc;

select product_name,total_sales from (
	select product_name,sum(total_sales) as total_sales,rank() over(order by sum(total_sales) asc) as rnk
	from gold.fact_sales a left join gold.dim_products b
	on a.product_key=b.product_key group by product_name)t
where rnk<=5;


--time based analysis
--find year yoy growth

WITH yearly_sales AS (
    SELECT 
        YEAR(order_date) AS years,
        SUM(total_sales) AS current_sales
    FROM gold.fact_sales
    WHERE order_date >= '2011-01-01'
    GROUP BY YEAR(order_date)
)

SELECT 
    years,
    current_sales,
    LAG(current_sales) OVER (ORDER BY years) AS prev_year_sales,
    ROUND(
        (current_sales - LAG(current_sales) OVER (ORDER BY years)) * 1.0 
        / NULLIF(LAG(current_sales) OVER (ORDER BY years),0), 
        2
    ) AS yoy_growth
FROM yearly_sales
ORDER BY years;

--find monthly yoy 

WITH monthly_sales AS (
    SELECT 
        YEAR(order_date) AS years,
        MONTH(order_date) AS months,
        SUM(total_sales) AS current_sales
    FROM gold.fact_sales
    WHERE order_date >= '2011-01-01'
    GROUP BY YEAR(order_date), MONTH(order_date)
),
lagged AS (
    SELECT
        years,
        months,
        current_sales,
        LAG(current_sales) OVER (PARTITION BY months ORDER BY years) AS prev_year_sales
    FROM monthly_sales
)

SELECT
    years,
    months,
    current_sales,
    prev_year_sales,
    ROUND(
        (current_sales - prev_year_sales) * 1.0 / NULLIF(prev_year_sales,0),
        2
    ) AS yoy_growth
FROM lagged
ORDER BY years, months;

--cumulative sales monthly

with monthly_sales as (
SELECT 
    YEAR(order_date) AS years,
    MONTH(order_date) AS months,
sum(total_sales) as total_sales
FROM gold.fact_sales
group by YEAR(order_date) , MONTH(order_date))
select years, months, sum(total_sales) over(partition by years order by months) from monthly_sales;

-- delivery time
select * from gold.fact_sales

select order_number,DATEDIFF(DAY,order_date,shipping_date) from gold.fact_sales;


--Numbers of active customers from the cohort

with cohort_months as (
select customer_key, 
dateadd(MONTH,datediff(MONTH,0,min(order_date)),0) as cohort_month
from gold.fact_sales
group by customer_key)

select a.cohort_month, 
dateadd(month,datediff(month,0,b.order_date),0) as monthly_orders,
DATEDIFF(MONTH, a.cohort_month, b.order_date) as cohort_index,
count(distinct b.customer_key) as no_of_active_customer  from cohort_months a join gold.fact_sales  b
on a.customer_key=b.customer_key 
where cohort_month is not null
group by 
a.cohort_month,
dateadd(month,datediff(month,0,b.order_date),0),
DATEDIFF(MONTH, a.cohort_month, b.order_date)
order by a.cohort_month, cohort_index

